services:
  frontend:
    container_name: frontend
    image: nginx:1.31.1
    restart: always
    networks:
      - main-network
    ports:
      - 80:80
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    container_name: backend
    image: maven:3.9.11-sapmachine-21
    restart: always
    networks: 
      - main-network
    ports:
      - "8080:8080"
    working_dir: /workspace
    volumes:
      - ./backend:/workspace:rw
      - ../secrets:/workspace/src/main/resources/secrets:ro # 컨테이너 내 secrets폴더 복사
      - maven_cache:/root/.m2  # 의존성 재설치 방지용도
    environment:
      - RSA_PUBLIC_KEY=classpath:secrets/public.pem
      - RSA_PRIVATE_KEY=classpath:secrets/private.pem
    command: ["./mvnw", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-Dspring.devtools.restart.enabled=true"]

  # backend:
  #   container_name: backend
  #   build:
  #     context: ./backend
  #     dockerfile: dockerfile
  #   env_file:
  #     - ./backend/.env
  #   image: backend:1
  #   restart: always
  #   networks:
  #     - main-network
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ../secrets:/app/resources/secrets:ro

  # neo4j:
  #   container_name: neo4j
  #   image: neo4j:5.26.26
  #   restart: always
  #   networks:
  #    - main-network
  #   ports:
  #     - 7474:7474
  #     - 7687:7687
  #   volumes:
  #     - neo4j_data:/var/lib/neo4j
  #     - neo4j_data:/data
  #     - neo4j_data:/logs
  #   environment:
  #     - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
  #     - NEO4JLABS_PLUGINS='["apoc"]' 
  #     - NEO4J_dbms_security_procedures_unrestricted=apoc.*
  #     - NEO4J_dbms_security_procedures_whitelist=apoc.*
  #     - NEO4J_dbms_security_procedures_allowlist=apoc.*

volumes:
  maven_cache: # 의존성 설치 볼륨
  # neo4j_data:  

networks:
  main-network: 
    driver: bridge

  # mariadb:
  #   container_name: mariadb
  #   image: mariadb:12.1.2
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   networks:
  #     - main-network
  #   volumes:
  #     - ./.mariadb/conf.d:/etc/mysql/conf.d:ro
  #     - ./.mariadb/initdb.d:/docker-entrypoint-initdb.d:ro
  #     - data-mariadb:/var/lib/mysql:rw
  #   environment:
  #     - MARIADB_HOST=localhost
  #     - MARIADB_PORT=3306
  #     - MARIADB_ROOT_PASSWORD=1234
  #     - MARIADB_DATABASE=edu
  #     - TZ=Asia/Seoul
  #     - LC_ALL:en_US.UTF-8

# volumes:
#   data-mariadb:
