server:
  port: 8080
  servlet:
    session:
      timeout: 30s

spring:
  application:
    name: backend
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: ${MARIADB_DRIVER}
    url: ${MARIADB_URL}
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
  ai:
    ollama:
      # base-url: http://192.168.0.108:11434
      base-url: ${OLLAMA_HOST}
      chat:
        options:
          # model: llama3:latest # ${OLLAMA_MODEL}
          model: ${OLLAMA_MODEL}
          format: json
          temperature: 0
  neo4j:
    # uri: bolt://192.168.0.205:7687
    uri: ${NEO4J_URI}
    authentication:
      # username: neo4j
      username: ${NEO4J_USER}
      # password: password123
      password: ${NEO4J_PASSWORD}
  kafka:
    # bootstrap-servers: 192.168.0.205:9094
    bootstrap-servers: ${KAFKA_SERVER}
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: false
    sampling:
      probability: 1.0

springdoc:
  swagger-ui:
    path: /docs
    operationsSorter: method

rsa:
  public-key: ${RSA_PUBLIC_KEY}
  private-key: ${RSA_PRIVATE_KEY}

token:
  expire:
    access: 30
    refresh: 2592000

logging.level.org:
  springframework.security: DEBUG #trace