name: Windows PC Job

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: self-hosted
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: .
      
      - name: Create .env file
        shell: cmd
        run: |
          echo MARIADB_DRIVER=${{ secrets.MARIADB_DRIVER }} > backend\.env
          echo MARIADB_URL=${{ secrets.MARIADB_URL }} >> backend\.env
          echo MARIADB_USER=${{ secrets.MARIADB_USER }} >> backend\.env
          echo MARIADB_PASSWORD=${{ secrets.MARIADB_PASSWORD }} >> backend\.env
          echo RSA_PUBLIC_KEY=${{ secrets.RSA_PUBLIC_KEY }} >> backend\.env
          echo RSA_PRIVATE_KEY=${{ secrets.RSA_PRIVATE_KEY }} >> backend\.env
      
      # - name: Build Java
      #   working-directory: ./backend
      #   run: .\mvnw.cmd clean package -DskipTests

      - name: Docker Down
        working-directory: .
        run: docker compose down
        continue-on-error: true

      - name: Docker Up
        working-directory: .
        run: docker compose up -d --build
